mitakarb/beerkeeper

- bin/setup
Yarnのインストールを行うようにする。
Yarnの依存関係がインストールされていない状況で`bin/setup`を実行すると、`db:prepare`のタイミングで落ちていたため。
> Fix bin/setup

- package.json
- yarn.lock
セキュリティアラート対応のため serialize-javascript をバージョンアップしました。
https://github.com/mitakarb/beerkeeper/network/alert/yarn.lock/serialize-javascript/open
> serialize-javascript  version up to 2.12.2

- bin/rails
Ruby 2.7.2 から非推奨な警告がデフォルトでは出なくなるので明示的に警告が出るようにしてみる
see: https://www.ruby-lang.org/ja/news/2020/10/02/ruby-2-7-2-released/
* 完全に動作未確認なので https://github.com/mitakarb/beerkeeper/pull/46 がマージされたら動作確認するぞい
* bin/rails だと rspec 実行時に引っかからない気がするのでそのあたりも考慮する必要がありそう（sidekiq みたいなミドルウェア使ってる場合とかも
> Ruby 2.7.2 から非推奨な警告がデフォルトで出なくなるので明示的に表示するようにする

- Gemfile
- Gemfile.lock
`webdrivers` gemをインストールすることで、各自の環境に`chromedriver`などをインストールしなくてもよくなります。
> Bundle webdrivers

- app/controllers/events_controller.rb
- app/views/events/_form.himl
- 自分以外の他人が主催者になることはない
- formの項目を減らすため
> イベント主催者をcurrent_userに限定する

- Dockerfile
従来のやり方だと、COPYコマンドで直前にインストールした
`node_modules`ディレクトリを上書きしていたっぽい。
> Dockerfileで`yarn install`をCOPYの後に行う

- Dockerfile
- Gemfile.lock
2.2.19を利用すると、Docker利用時に
```
web_1  | bundler: failed to load command: rails (/usr/local/bundle/bin/rails)
web_1  | /usr/local/bundle/gems/bundler-2.2.19/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find msgpack-1.4.2 in any of the sources (Bundler::GemNotFound)
```
のようなエラーが出る。
2.2.5は以前使っていたバージョンで、こちらでは正常に動くことを確認できた。
しばらくしたら最新版を試すとして、今は2.2.5で動かしたい。
Ref: #74
> Bundlerのバージョンを2.2.5に固定

- .github/dependabot.yml
Dependabotは設定ファイルがないと動かなくなっているのでは、という懸念があるため（`webpacker`とか古いままになっている）。
> Dependabotの設定ファイルを追加

- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/assets/stylesheets/application.bootstrap.scss
- app/assets/stylesheets/application.scss
- app/javascript/application.js
- app/javascript/src/application.scss
- config/importmap.rb
適用させるために assets配下の `scss`ファイルに `@import "bootstrap"` を記述し適用させています。
gemなしでやる場合、 css-bundlingをいれて `package.json` `yarn` でBootstrapをいれなければいけないようです。
nodejsを完全に剥がせると思ったのですが、依存gemの`execjs`がnodeを要求しているため剥がせず。。（tailwindなら剥がせるかもしれません（未検証））
> Bootstrapの適用

- docker-compose.yml
Dockerで環境構築をした場合、beerkeeperディレクトリ配下に`beerkeeper/tmp/pids`が作成されていた。
docker-compose.ymlのtmpfsの指定を、beerkeeperディレクトリ配下の`tmp/pids`にするように修正。
Dockerコンテナ内は`/app`がbeerkeeperのRAILS_ROOTになるため、beerkeeperディレクトリは不要
- 変更前
- `/app/beerkeeper/tmp/pids`
- 変更後
- `/app/tmp/pids`
> docker-compose.yml tmpfsのpidsディレクトリのパスを修正

- app/controllers/registrations_controller.rb
> サインアップ時の画面はログイン画面に誘導する

- Dockerfile
- Gemfile
- Gemfile.lock
- docker-compose.yml
- spec/support/capybara.rb
- spec/system/events_spec.rb
- spec/system/participations_spec.rb
- spec/system/registrations_spec.rb
- spec/system/sessions_spec.rb
chromiumに変更。M1 Macでは動いたので、AMD64なWin機などで動作確認した後にWIP外しますー
```
docker compose run --rm -e RAILS_ENV=test web bundle exec rspec
[+] Creating 2/0
✔ Container beerkeeper-redis-1  Running                                                                              0.0s 
✔ Container beerkeeper-db-1     Running                                                                              0.0s 
*..........I, [2023-09-14T11:52:12.452155 #49]  INFO -- : Removed /app/public/assets
Pending: (Failures listed here are expected and do not affect your suite's status)
1) Event add some examples to (or delete) /app/spec/models/event_spec.rb
Finished in 3.42 seconds (files took 1.2 seconds to load)
11 examples, 0 failures, 1 pending
```
以前、M1 Macで`docker compose up`したらこうなってた
```
$ docker compose up
=> ERROR …
```
> Dockerfile のM1 Mac対応

- app/models/user.rb
同じemailで登録しようとするとDB側のユニーク制約に引っかかりエラーが発生するので、rails側で定義しているemailのvalidationにもユニーク制約を追加した。（メールアドレスの大文字・小文字の区別までは見ないようにしています）
> emailにユニークを確認するバリデーションを追加

- .github/dependabot.yml
https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> chore: dependabotの監視にgithub actionsのactionのバージョンを追加

- .devcontainer/devcontainer.json
- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
vs codeでdevcontainerを使えるようにする
docker起動＋↓の拡張機能を入れて
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
左下の青ポチをクリックしてコンテナで開く
抜ける場合は同じところをクリックしてclose remote connection
ターミナルはコンテナ内で叩くことになるので、`docker compose --rm web` 的なのは不要
> Add devcongainer

- app/models/event.rb
- app/views/events/show.html.erb
- config/application.rb
- config/locales/ja.yml
- spec/factories/events.rb
> タイムゾーンをTokyoに設定し、イベント日時をフォーマット表示・開始日時・終了日時の必須バリデーションを追加

- app/models/event.rb
- spec/models/event_spec.rb
- 🎫: fix #797 
- Why?
- userがnilの時がある
- What?
- nilのときはnil返す
> 未ログイン状態でイベント詳細を表示するとエラーの修正

- Gemfile
- Gemfile.lock
rspecがうまく動かない問題が解消されたため
- 🎫:
- Why?
- What?
> :arrow_up: bootstrap gemのバージョンを最新の固定バージョンにする

- config/initializers/new_framework_defaults_8_0.rb
- Why?
- refs. [Railsのnew\_framework\_defaultsとの向き合い方 \- Money Forward Developers Blog](https://moneyforward-dev.jp/entry/2022/05/18/new_framework_defaults-for-rails/)
- new_framework_defaults は load_defaults を該当バージョンに上げるまでは残しておかないとダメでした。
- What?
- 「要らないんじゃね？」と言って消してしまってすいませんでした 🙏
> new_framework_defaults_8_0.rb を復活させる

- .github/workflows/ruby_head_specs.yml
- 🎫:
- Why?
ruby_head_spec.yml を手動実行可能にするため
- What?
`workflow_dispatch`を上記ymlに追加
> ruby_head_spec.yml に workflow_dispatch を追加

- app/views/layouts/application.html.erb
- 🎫: https://github.com/mitakarb/beerkeeper/issues/94
- Why? 使いにくいため
- What? 幅を狭くしても見えるようにした
memo:
そのうちTailwindにしたい
> Fix #94 無理やりだけどBootstrapは古いので、いったんこれで
