mitakarb/beerkeeper

Gemfile, Gemfile.lock
- dependabotが[PR](https://github.com/mitakarb/beerkeeper/pull/5 )を作ってくれていたけど面白そうだったので一気に最新版へupdate
=> Update puma from 3.12.1 to 4.3.1

app/javascript/packs/application.js, app/javascript/src/application.scss, package.json, yarn.lock
=> :+1: add bootstrap

yarn.lock
セキュリティアラートを解消したかったので
`yarn upgrade` しました
=> yarn upgrade 2020/05/14

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/views/layouts/application.html.erb, app/views/sessions/new.html.himl, config/routes.rb, spec/requests/sessions_request_spec.rb
=> Loginフォームを追加

app/views/events/index.html.himl
[新規作成]リンクをログインしていない状態では表示しないようにしました。
=> Switch new event link visibility

app/controllers/events_controller.rb, app/models/event.rb, app/models/user.rb
- UserモデルとEventモデル間にアソシエーションを追加
=> Add associations

app/views/events/index.html.himl, app/views/layouts/application.html.erb
=> ヘッダーとイベント一覧ページにスタイルを追加

app/views/events/show.html.himl
=> イベント詳細ページのデザイン修正

README.md
つくってみたけど、こんなシンプルでいいですかねえ…(?_?)
=> READMEを作ってみた

Dockerfile, babel.config.js, bin/webpack, bin/webpack-dev-server, config/database.yml, config/webpacker.yml, docker-compose.yml, entrypoint.sh, package.json, yarn.lock
たぶん動きますが、database.yml含めて変更が大きいのでなんかいい感じにしたいです（語彙力
https://docs.docker.com/compose/rails/
https://qiita.com/naokit-dev/items/99225bf3d8665ecfdec2
=> add docker-compose

config/database.yml
host, username, databaseが対象。
Docker環境のための値がハードコードされているので、環境変数を設定すればローカル環境で動作するようにしたかった。
=> `config/database.yml`内の設定を環境変数から読み込むようにした

Gemfile, Gemfile.lock, spec/spec_helper.rb, spec/system/events_spec.rb
=> Add spec/system/events_spec.rb

.github/workflows/rubocop-analysis.yml
=> Fix rubocop action

Gemfile, Gemfile.lock, babel.config.js, package.json, yarn.lock
`yarn upgrade`を打ったので差分がすごいことに…
=> Update npm packages

app/views/layouts/application.html.erb
fix: https://github.com/mitakarb/beerkeeper/issues/96
=> ロゴのリンクをルートにした

.github/workflows/run_specs.yml, Dockerfile, Gemfile, Gemfile.lock, README.md, docker-compose.yml, spec/spec_helper.rb
Docker を使っている人も多く、System Spec を Docker でも動かしたかったので、動くようにしてみました
主に https://sinsoku.hatenablog.com/entry/2021/03/24/100000 を参考にさせてもらいました〜
=> Systemspec on docker

spec/spec_helper.rb
System Spec実行時にワーニングが出ていたので、出ないようにした
最近は設定頑張らなくてもよくなってうれしい〜〜〜
=> Fix system spec warning

app/controllers/events_controller.rb, app/models/event.rb
=> 未ログインユーザがイベントを編集できてしまう不具合の解消

Dockerfile
Update nodejs version from 18 to 20.
fix #626
=> Update nodejs version from 18 to 20

app/models/event.rb, spec/models/event_spec.rb
=> イベント名の必須入力のバリデーションを追加

app/controllers/events_controller.rb
https://github.com/mitakarb/beerkeeper/issues/734
=> Notification when not an organizer

app/models/event.rb, app/views/events/show.html.erb
=> オーガナイザーではない場合に、編集ボタンと削除ボタンは表示させない #738

config/locales/ja.yml
| 編集前 | 編集後 | 
| --- | --- |
| ![スクリーンショット 2024-05-02 20 57 20](https://github.com/mitakarb/beerkeeper/assets/81839214/a97cfa03-235a-4327-b19b-f06520de16c4) | ![スクリーンショット 2024-05-02 21 39 09](https://github.com/mitakarb/beerkeeper/assets/81839214/56d40ca4-22df-41f9-9111-9ce91079526f) |
=> Fix #798: 編集画面のラベルをわかりやすくした。

.github/workflows/dependabot_auto-merge.yml
- 🎫: nil
- Why? dependabotのPRを自動マージしたい！
- What? ↑の設定をした
=> Add Dependabot auto-merge

app/controllers/events_controller.rb, app/models/event.rb
=> 参加者がいるイベントを削除しようとするとエラー 

compose.yaml
- 🎫: close https://github.com/mitakarb/beerkeeper/issues/858
- Why?: Good First Issueとして
- What?: redis を 7 にあげました 🚀
=> Bump redis 7

README.md
- 🎫:
- Why?
- httpsでのcloneだと、毎度パスワードを求められる（はず）なので、sshでやるように案内する
- What?
=> :memo: Update readme 20241114

bin/dev
```ruby
ActionView::Template::Error (The asset 'application.css' was not found in the load path.)
Caused by: Propshaft::MissingAssetError (The asset 'application.css' was not found in the load path.)
Information for: ActionView::Template::Error (The asset 'application.css' was not found in the load path.):
6:     <%= csrf_meta_tags %>
7:     <%= csp_meta_tag %>
8:     <%= favicon_link_tag('favicon.ico') %>
9:     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
10:     <%= javascript_importmap_tags %>
11:   </head>
12: 
app/views/layouts/application.html.erb:9
Information for cause: Propshaft::MissingAssetError (The asset 'application.css' was not found in the load path.):
app/views/layouts/application.html.erb:9
```
詳細 …
=> 'application.css' がないって言われちゃうので、以前のbin/devに戻しました
